### ISSUE TITLE
Requests suddenly don't perform

### ISSUE THREAD

**Issue by RuS2m** [ADKosm/ActiveFlow#1]
![image](https://user-images.githubusercontent.com/34570656/47220185-bc845600-d3b9-11e8-9c1d-7d7ee9d87ccb.png)

**Comment by ADKosm** [comment]
Fix this problem in 6042ef2fa1443db15c63488f576cf204fa43e441 
The official app in the store should update automatically

**Comment by RuS2m** [comment]
@ADKosm, that actually didn't solve problem
![image](https://user-images.githubusercontent.com/34570656/47257144-dc3b7d00-d492-11e8-9c36-67d4ec47b055.png)

**Comment by RuS2m** [comment]
I suppose something wrong with web server side, because everything is fine with Inetrnet connection)
